export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FETCHING = 'LOGIN_FETCHING'  
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'

export const ADMIN_SUCCESS = 'ADMIN_SUCCESS'
export const ADMIN_FETCHING = 'ADMIN_FETCHING'
export const ADMIN_FAILED = 'ADMIN_FAILED'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const NIKE_FETCHING = 'NIKE_FETCHING'    
export const NIKE_SUCCESS = 'NIKE_SUCCESS'
export const NIKE_FAILED = 'NIKE_FAILED'  

export const ADIDAS_FETCHING = 'ADIDAS_FETCHING'
export const ADIDAS_SUCCESS = 'ADIDAS_SUCCESS'  
export const ADIDAS_FAILED = 'ADIDAS_FAILED'

export const PUMA_FETCHING = 'PUMA_FETCHING'    
export const PUMA_SUCCESS = 'PUMA_SUCCESS'
export const PUMA_FAILED = 'PUMA_FAILED'

export const REEBOX_FETCHING = 'REEBOX_FETCHING'
export const REEBOX_SUCCESS = 'REEBOX_SUCCESS'
export const REEBOX_FAILED = 'REEBOX_FAILED'

export const UNDERARMOUR_FETCHING = 'UNDERARMOUR_FETCHING'
export const UNDERARMOUR_SUCCESS = 'UNDERARMOUR_SUCCESS'
export const UNDERARMOUR_FAILED = 'UNDERARMOUR_FAILED'

export const URL_IMG = 'http://localhost:8000'


